### ISSUE TITLE
SpousteciUdalost by měla být číselník (6.1.7)

### ISSUE THREAD

**Issue by kosek** [nsessl/schema#1]
Současné schéma `nsess.xsd` definuje

````xml
<xs:element name="SpousteciUdalost" type="xs:string">
  <xs:annotation>
	<xs:documentation xml:lang="cs">Prvek pro zaznamenání kritéria, kterým je stanoven začátek plynutí skartační lhůty.</xs:documentation>
  </xs:annotation>
</xs:element>
````

Vyhláška přitom říká:

> ESSL umožňuje správcovské roli stanovit pro každou věcnou skupinu jednu z následujících spouštěcích událostí
> a)	rok vyřízení spisu,
> b)	rok uzavření spisu, typového spisu, součásti typového spisu nebo dílu typového spisu,
> c)	rok založení spisu totožný s rokem jeho evidence,
> d)	rok narození nebo vzniku subjektu,
> e)	externí událost, u které nelze předem stanovit okamžik vzniku spouštěcí události (například formou užití slov „po skončení platnosti smlouvy“, „od likvidace skládky“ nebo „po zahájení insolvenčního řízení“) s počtem let, po jejichž uplynutí eSSL vyzve posuzovatele skartační operace k posouzení, zda již externí spouštěcí událost nastala.

Bod e) připouští vložení volného textu, ale body a-d nedefinují jaká hodnota se má přenášet a tím pádem bude problém s výměnou dat mezi systémy.

**Comment by karelskrle** [comment]
To je velká škoda. Základní špoštěcí události jste vyjmenoval. Průblém činí nedefinované pojmenování základních typů. Pro externí spouštěcí událost je pak vhodné umožnit doplnění spouštěcího okamžiku textem. Navíc je nešťastné, že spouštěcí okamžik je svázán přímo se skartačním režimem a ne s věcnou skupinou nebo druhem dokumentu. Je nesmyslné dělat desítky kombinací skartačních režimů pro různé lhůty.

**Comment by kosek** [comment]
Těch nešťastných věcí je tu více :-(

Issue jsem znovu otevřel a označil pro dořešení v další verzi.
