### ISSUE TITLE
Nekonzistentní pojmenování elementů

### ISSUE THREAD

**Issue by kosek** [nsessl/schema#12]
I v jednom schématu jsou nekonzistence, např.:

* SpisId, IdSpis, IdSpisu -- nejpoužívanější je SpisId
* DokumentId, IdDokumentu -- nejpoužívanější je IdDokument

Kvůli zpětné kompatabilitě asi nemá cenu pro v2023 opravovat

**Comment by OAS-Prochazka** [comment]
Problém byl odstraněn v národním standardu platném od 1. 9. 2024, sjednoceno na SpisId a DokumentId
