### ISSUE TITLE
sTypDokumentu - neobsahuje identifikátor, ani další údaje

### ISSUE THREAD

**Issue by KlaraZan** [nsessl/schema#18]
sTypDokumentu - podle nového standardu by se měl jmenovat sDruhDokumentu. 
Element by měl obsahovat identifkátor, aby s ním bylo možné manipulovat stejně jako s ostatními číselníky. 
Podle nového standardu by měl též obsahovat volitelně skartační režim a příp. další specifické prvky

**Comment by kosek** [comment]
Díky, změněno.
