### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by pacovskyvera** [nsessl/schema#23]
Nekonzistentní pro různé typy schemat (např. http://www.mvcr.cz/nsesss/2023/api; http://www.mvcr.cz/nsesss/2023/log;; http://www.mvcr.cz/nsesss/v4)

**Comment by kosek** [comment]
MVČR bohužel nemá žádnou ustálenou konvenci natož metodiku, jak generovat jmenné prostory a pracovat se verzemi.

`http://www.mvcr.cz/nsesss/v4` navazuje na předchozí jmenný prostor `http://www.mvcr.cz/nsesss/v3` akorát se změnilo číslo odpovídající verzi, protože ve schématu byly provedeny zpětně nekompatibilní změny.

Jmenné prostory typu `http://nsess.public.cz/erms/v_02_00` používané zejména v příloze 1 nejsou dále používány, protože doména public.cz není ve vlastnictví MVČR a ani nijak nesouvisí s problematikou spisových služeb. Schémata v příloze 1 a 2 spolu přímo nesouvisí a jsou i jinak číslována, takže držet se jednotného čísla verze moc nejde.

Osobně bych klidně místo `http://www.mvcr.cz/nsesss/v4` použil  http://www.mvcr.cz/nsesss/2023`, ale to by se zase nelíbilo někde jinde ;-)

**Comment by pacovskyvera** [comment]
Např. schéma http://www.mvcr.cz/nsesss/2023/log pro transakční protokol přímo souvisí se schématem v4 jelikož se oba ukládají do SIPbalíčku...
