### ISSUE TITLE
Textová část NSESSS vs schémata

### ISSUE THREAD

**Issue by pacovskyvera** [nsessl/schema#24]
V textové části neuvedeny metody:
 
SYN:
CiselnikySeznam
DokumentVraceniZadost
FunkcniMista
OsobySeznam
SpisVraceniZadost
UzivateleSeznam
 
ASYN:
DokumentUzavreni
DokumentVraceni
SpisVlozeniDoTypovehoSpisu
SpisVyjmutiZTypovehoSpisu
Zprava

**Comment by kosek** [comment]
Textovou částí myslíte samotný text národního standardu?

Text standardu se ještě upravuje, aby v něm seznamy služeb a událostí byly v souladu se samotnou definicí rozraní. Každopádně zajistím, aby se to před vydáním ještě jednou zkontrolovalo.

**Comment by OAS-Prochazka** [comment]
Provedl jsem srovnání s textem NSESSS a výsledek poslal e-mailem to kosek.
[Textová část NSESSS vs schémata.docx](https://github.com/nsessl/schema/files/11796146/Textova.cast.NSESSS.vs.schemata.docx)
