### ISSUE TITLE
ASYN: OdkazVytvoreni

### ISSUE THREAD

**Issue by pacovskyvera** [nsessl/schema#28]
Namísto TypVazby použít DuvodId nebo DuvodText,  nekoresponduje s profilovými údaji dokumentu/spisu, resp. Není jasná role elementu SouvisejiciDokument, ideálně vysvětlit vzájemnou závislost

**Comment by kosek** [comment]
SouvisejiciDokument bylo i v předcházející verzi rozhraní, k čemu se to používalo nevím, ale vzhledem k požadavku na co nejmenší změny, byl tento element v rozhraní ponechán.

Připravovaný standard vyžaduje události pro vytváření a mazání odkazů. Pevné odkazy mohou být jen mezi spisy, a gProfilSpisu obsahuje element KrizoveOdkazyPevne, takže OdkazVytvoreni a OdkazZruseni budou manipulovat s těmi daty, pokud půjde o pevné odkazy. Volné odkazy mohou být teoreticky mezi jakoukoliv entitou, ale v praxi to bude nejspíše zase jen spis a dokument a v obou je k dispozici element KrizoveOdkazyVolne.

Vzhledem k tomu, že KrizoveOdkazyPevne/KrizoveOdkazyVolne neobsahují žádná další metadata než cíl odkazu (zdroj je dán implicitně tím, kde je odkaz uveden) a nic takového nevyžaduje ani standard, nevidím důvod přidávat informaci o "důvodu" odkazu.

Pokud si systémy potřebují nějaký "důvod" poslat, mohou na to použít DoplnujiciData a zavést si vlastní konvenci. Pokud by to byl častější požadavek, může se zvážit úprava standardu a schémat v nějaké jejich budoucí verzi.
