### ISSUE TITLE
Délky datových polí - subjekt a adresa

### ISSUE THREAD

**Issue by pacovskyvera** [nsessl/schema#29]
Sladění délek datových polí pro jméno, příjmení, název dle ZR, data která budou předávana přes rozhraní vč. Zahraničních subjektů

**Comment by kosek** [comment]
Můžete mne prosím odkázat na zdroj informací o délkách polí dle ZR. Marně se to snažím najít a dostal jsem informaci, že ty trochu podivně nastavené délky v předchozí verzi jsou takto nastaveny schválně a správně. ;-)

**Comment by pacovskyvera** [comment]
Odkaz na schémata by měl být zde: 

https://www.szrcr.cz/images/dokumenty/v%C3%BDvoj%C3%A1%C5%99i/egon_20221205.zip

**Comment by kosek** [comment]
OK, upravil jsem

**Comment by frantisekfialagordic** [comment]
Položka sObchodniNazev by mala být 255 znaků. Podle schemat MF ČR - například některé názvy veselých politických stran jsou extrémně dlouhé.

https://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1/uvis_datatypes_v_1.0.1.xsd

```lang=xml
	<xsd:simpleType name="obchodni_firma" id="AA0020">
		<xsd:annotation>
			<xsd:documentation xml:lang="cs">nĂˇzev obchodnĂ­ firmy</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="255"/>
		</xsd:restriction>
	</xsd:simpleType>
```
