### ISSUE TITLE
SYN: PrideleneSeznam

### ISSUE THREAD

**Issue by pacovskyvera** [nsessl/schema#30]
Druh entity by měl být povinný a z hlediska optimalizace vyhledávat pouze konkrétní typ entity (tomu odpovídá i stávající response, který poskytuje seznam entit v rámci choice (jeden ze seznamů entit). V opačném případě je nutné response koncipovat na oddělená pole podle jednotlivých typů entit.

**Comment by jakub-ruzicka** [comment]
Mě naopak přijde správná cesta úprava PrideleneSeznamResponsezměna, umožnit v rámci response odeslat  současně  více typů entit.
Pokud by bylo potřeba volání optimalizovat, tak může volající strana doplnit druh entity.

**Comment by pacovskyvera** [comment]
Moc nechápu uzavření tohoto našeho issue "SYN: PrideleneSeznam" Je tam uzavření "closed this as completed in 59decbb 2 days ago", ale odkazuje se to na dle mého názoru zcela nesouvisející úpravu.

**Comment by kosek** [comment]
Asi jsem se překlepl v čísle issue. Otevírám.

**Comment by OAS-Prochazka** [comment]
Problém byl odstraněn v národním standardu platném od 1. 9. 2024, odebrána entita Typový spis - typový spis nelze přes rozhraní přidělit.
