### ISSUE TITLE
Nadbytečné elementy v gSpisZakladniProfil

### ISSUE THREAD

**Issue by karelskrle** [nsessl/schema#33]
Spis není evidován v podacím deníku ani není nařízena evidence, pro mi elementy PodaciDenik, PodaciDenikRok, PodaciDenikPoradi považuji za irelevantní ve skupině gSpisZakladniProfil.

**Comment by frantisekfialagordic** [comment]
Předpokládám že bude muset být zachováno minimálně pro stará data.

**Comment by kosek** [comment]
Prozatím ponecháme. 

V budoucnu můžeme odstranit, ale až po důkladné analýze, zda elementy opravdu nejsou potřeba.
