### ISSUE TITLE
Název elementu TypDokumentu má být přejmenován na DruhDokumentu

### ISSUE THREAD

**Issue by karelskrle** [nsessl/schema#34]
S ohledem na změnu textu NSESSS by měl být přejmenován TypDokumentu na DruhDokumentu. Např. v požadavku 8.1.28 je přímo odkaz na DruDokumentu.

**Comment by kosek** [comment]
Tady se naráží na problém toho, zda dát přednost důslednému aplikování nové terminologie, nebo zpětné kompatibilitě. Při úpravě schémat byl jeden z hlavních požadavků zachovat co nejvíce kompatibilitu s předchozí verzí. Změna názvu elementu v tomto případě by znamenala jen úpravu kódu v X aplikacích, ale z hlediska funkčnosti by nic nového nepřinesla.

Nicméně jsem do komentářů schémat alespoň na více místech doplnil informaci o tom, že v elementu se přenáší druh dokumentu (viz https://github.com/nsessl/schema/commit/032abb34aca0840570a2c774953b125a54654742).

Pokud vám to přijde jako přijatelné řešení, prosím o uzavření issue.

**Comment by kosek** [comment]
Vzhledem k tomu, že druh dokumentu může obsahovat i další údaje jako skartační režim, byla změna provedena.
