### ISSUE TITLE
ASYN: SpisOdebran, DokumentOdebran

### ISSUE THREAD

**Issue by pacovskyvera** [nsessl/schema#35]
Hrozí vznik nekonzistence dat pro zatím nezpracované události.

**Comment by kosek** [comment]
Ano, tento problém dané události přináší a již se diskutoval. Nicméně pracovní skupina trvala na ponechání těchto událostí ve standardu.

**Comment by pacovskyvera** [comment]
A s jakým závěrem se diskutoval? Jaká je tedy metodika MV proto aby nedošlo k nekonzistenci dat? 
Pokud je zaslána událost SpisOdebran asny. Druhý systém bude nadále pracovat se spisem vytvoří desítky událostí ty zašle a než dojde ke zpracování dané události dojde k nekonzistenci…

**Comment by kosek** [comment]
WG rozhodla, že se může dát pryč
