### ISSUE TITLE
TypDokumentu v profilu spisu, návrh na změnu na DruhSpisu

### ISSUE THREAD

**Issue by karelskrle** [nsessl/schema#38]
NSESSS neuvádí vztah TypuDokumentu, resp. DruhDokumentu ke spisu. Nicméně je vhodné nějakou klasifikaci pro spis používat. Tato klasifikace zpravidla není totožná s klasifikací dokumentu a jsou klienty požadovány odlišné číselníky. Navrhuji nahradit TypDokumentu v profilu spisu elementem DruhSpisu. 
Pozn. pro zpětnou kompatabilitu se plnit DruhDokumentu i DruhSpisu z jednoho zdroje.

**Comment by kosek** [comment]
Díky, opraveno. Viz https://github.com/nsessl/schema/commit/59decbb87e364ab91b527880cd7367e2a9ad2573
