### ISSUE TITLE
Přidat doplňující data k zásilce 

### ISSUE THREAD

**Issue by karelskrle** [nsessl/schema#42]
Navrhujeme rozšířit ZasilkaInfoZakladni o doplňující data. V některých případech je nutné přenášet další údaje nad základní rozsah metadat. Např. u vyvěšení na úřední desku nebo u hybridní pošty. A v případě použití metody DokumentPostoupeni není možné potřebné údaje k zásilce předávat.

**Comment by kosek** [comment]
OK, doplněno
