### ISSUE TITLE
Stavy spisů (sStavSpisu) a dílu (sStavDiluSoucastiTS)

### ISSUE THREAD

**Issue by LechnerTomas** [nsessl/schema#44]
sStavSpisu
 -  chybí stav znepristupnen jako výsledek události SpisZrusen

sStavDiluSoucastiTS
 - domnívám se, že stavy dílů by měly být shodné se stavy spisů sStavSpisu

**Comment by jakub-ruzicka** [comment]
Pokud by se zasahovalo do sStavSpisu, bylo by vhodné doplnit stav Ztracen

**Comment by LechnerTomas** [comment]
Souhlasím, ale pak totéž i k dokumentu
