### ISSUE TITLE
Zmizela událost "DokumentPredaniDoSpisu"

### ISSUE THREAD

**Issue by LechnerTomas** [nsessl/schema#48]
Oproti původnímu návrhu zmizela událost "DokumentPredaniDoSpisu"

**Comment by LechnerTomas** [comment]
Možná jsem to nepochopil, ale obávám se, že to úplně nenaplňuje:
 - DokumentPostoupeni - vlastník předává dokument do správy novému systému, ERMS do ISSD
 - tím nad ním ztrácí možnost dělat operace, nemůže volat žádné další události nad tímto dokumentem, tedy ani vnutit vložení do spisu, který vlastní ISSD
 - Funkce měla dle mého názoru umožnit, aby ERMS mohla vložit dokument do spisu, který vlastní ISSD
 - což po DokumentPostoupeni již musí rozhodnout ISSD a ERMS do toho nemůže mluvit (dokument má po postoupení ve výhradním přístupu ISSD)
 - Je samozřejmě otázkou, zda tuto funkci umožnit, ale když v původním návrhu byla, tak ji asi někdo potřeboval, aby ERMS mohla vložit dokumentu do spisu, který vlastní ISSD
 - Takže ano, lze to nahradit, ale jedině tak, že ERMS volá DokumentPostoupeni a pak ISSD řekne, že vložila do spisu a dokument vrací pomocí DokumentVlozeniDoSpisu a DokumentVraceni, ale nevím, jak se spolu tyto dva systémy domluví, protože nebude cesta, jak si předají informaci, do kterého spisu se to má dokument vložit

**Comment by LechnerTomas** [comment]
Děkuji za reakci a souhlasím

**Comment by OAS-Prochazka** [comment]
Komentář garanta XML za ICT Unii: nikdo se k problematice nevyjádřil, není relevantní.
