### ISSUE TITLE
Omezit  tUdalostiSyn na 10 události

### ISSUE THREAD

**Issue by jakub-ruzicka** [nsessl/schema#50]
Vnímáme problém ve změně z 10 události na neomezeně. 
Problém může být velikosti volání, ale také s tím, že zpracovaní má proběhnout v jedné transakci (8.1.6).
10 událostí nám připadá dostatečné.

**Comment by kosek** [comment]
Tak předpokládejme, že autoři systémů budou mít rozum. Když tam necháme 10, někdo se bude ptát, proč to není 8 nebo třeba 20.

**Comment by jakub-ruzicka** [comment]
Nechci být příliš negativní, ale tento předpoklad není správný. Pokud to standard umožnuje tak se vždy najde někdo kdo to bude vyžadovat.  Pokud nebyl odůvodněný požadavek na změnu tak bych něco co funguje zbytečně neměnil.
