### ISSUE TITLE
Rozšíření gZasilkaInfoZakladni/PodaciCislo 

### ISSUE THREAD

**Issue by jakub-ruzicka** [nsessl/schema#51]
Element gZasilkaInfoZakladni / PodaciCislo  - MinLength 0, MaxLength 30  v praxi je to nedostatečné pro zásilky z ciziny.
Dáváme na zvážení změnu maximální velikosti.

**Comment by kosek** [comment]
OK, rozšířil jsem na 40 znaků, což by mělo stačit
