### ISSUE TITLE
Umožnit klasifikovat vztah mezi soubory (komponentami) v OdkazyNaSoubory

### ISSUE THREAD

**Issue by karelskrle** [nsessl/schema#53]
Postrádáme možnost klasifikovat vztah mezi komponentami jednoho dokumentu nebo zásilky v OdkazyNaSoubory/dmFileLink.
Stávající úprava umožnije doplnit související odkaz prostřednictvím elementu dmUpFileGuid, ale není možné zachytit klasifikaci tohoto vztahu. Např. je potřeba zachytit vztah, zda se jedná o výstup ze změny datového formátu, anaonymizace, podpis, kontejner, ve kterém byla komponenta apod.
Ústupová možnost je použití doplňujících dat.

**Comment by OAS-Prochazka** [comment]
Problém byl odstraněn v národním standardu platném od 1. 9. 2024, přidán číselník dmFileCategory
