### ISSUE TITLE
dmBaseTypes

### ISSUE THREAD

**Issue by krupkak** [nsessl/schema#54]
Bude se zakomponovávat aktualizace wsdl 3.0 s úpravami a rozšířením služeb v souvislosti s VoDZ? (odkazováno patrně pouze na dmId a idDb, samotrné služby jinde odkazovány ve schématech asi nejsou)

**Comment by kosek** [comment]
Ze schématu dmBaseTypes.xsd se využívají jen dva vámi zmíněné datové typy. Takže důvod aktualizace schématu zde není, definice těchto typů se nemění a upřímně by bylo nejlepší závislost na dmBaseTypes.xsd úplně zrušit.
