### ISSUE TITLE
Příloha 7 - PrenosPotvrzeni

### ISSUE THREAD

**Issue by krupkak** [nsessl/schema#55]
PrenosPotvrzeni/StatusPrenosu
PrenosPotvrzeni/StatusEntit/Entita/StatusPrenosu 

Doporučujeme rozšířit o upřesňující důvod nenačtení (částečného načtení) dávky či entity, např. chybou validace, neznámým uživatelem (vlastniKdo), chybějící hodnotou elementu apod.

**Comment by pacovskyvera** [comment]
Bylo by vhodné do dokumentačního komentáře doplnit popis, že je možné tam zasílat popis chyby, nebo důvod nenačtení.

**Comment by kosek** [comment]
Takový popis tam je
https://github.com/nsessl/schema/commit/45f91dc2c637a3f7fcbe0c63e8a4c7d7b3ea2248
