### ISSUE TITLE
Příloha 7 - sTypEntity

### ISSUE THREAD

**Issue by krupkak** [nsessl/schema#56]
1. Tento typ je samotný uveden v rámci ermsExportPrenos.xsd. Nelze rozšířit a následně tak využít společný typem sDruhEntity z ermsTypes?
2. Jaký je účel použití typu entity BinarniSoubor, v entitě Soubor se již nachází odkaz na binární soubor?

**Comment by kosek** [comment]
> Tento typ je samotný uveden v rámci ermsExportPrenos.xsd. Nelze rozšířit a následně tak využít společný typem sDruhEntity z ermsTypes?

Typy jsou rozdílné, protože při exportu dle přílohy 7 se musí exportovat "servisní objekty", které nejsou klasickou entitou z pohledu standardu (třeba seznam uživatelů).

> Jaký je účel použití typu entity BinarniSoubor, v entitě Soubor se již nachází odkaz na binární soubor?

OK, BinarniSoubor jsem dal pryč.
