### ISSUE TITLE
Různé restrikce pro Skartační lhůtu

### ISSUE THREAD

**Issue by hanus-jan** [nsessl/schema#58]
v _nsess-common.xsd_ je tato restrikce
<xs:restriction base="xs:integer">
      <xs:minInclusive value="**0**"/>
      <xs:maxInclusive value="999"/>
    </xs:restriction>

zatímco v _ermsTypes.xsd_ je restrikce
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="**1**"/>
      <xs:maxInclusive value="999"/>
    </xs:restriction>

**Comment by kosek** [comment]
Díky, sjednoceno

**Comment by hanus-jan** [comment]
Mohu se zeptat, která hodnota byla zvolena?
