### ISSUE TITLE
Příloha 2 - atribut Komponenty - analog_original

### ISSUE THREAD

**Issue by PavlinaN** [nsessl/schema#59]
Upozorňujeme na nekonzistenci při vytváření metadat komponent -  z našeho pohledu se analogové části dokumentu řeší na úrovni dokumentu (ukládací jednotka analogového dokumentu)

  <xs:attribute name="analog_original" type="xs:string">
      <xs:annotation>
        <xs:documentation>Pokud je forma uchování "digitalizát", je možné v tomto atributu uvést místo uložení analogového originálu.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

**Comment by kosek** [comment]
OK, atribut jsem dal pryč. Tuto informaci lze ukládat do elementu UkladaciJednotka
