### ISSUE TITLE
Element WsUrl - SouborNovaVerze × SouborZalozeni

### ISSUE THREAD

**Issue by hanus-jan** [nsessl/schema#60]
Je nějaký důvod proč je element WsUrl jen u některých metod, které pracují se soubory?

Např. pro SouborNovaVerze se element vyskytuje, ale pro SouborZalozeni již nikoliv.

Takže pro SouborZalozeni a možnost odkazem platí to, co do teď, tj. odkaz na stažení se musí sestavovat na základě identifikátoru. Co by měl systém pro SouborNovaVerze poslat v elementu WsUrl - odkaz přímo na stažení souboru? Nebo i v tomto případě se bude pracovat s identifikátorem souboru a skládat URL pro stažení souboru? Nebo to záleží na individuální implementaci?

**Comment by kosek** [comment]
Díky, evidentně se jedná o nekonzistenci, která byla i v předchozí verzi rozhraní. Je to opravené.
