### ISSUE TITLE
ULOHA-20230621-01: NSESSS - TERMINOLOGIE

### ISSUE THREAD

**Issue by JaroslavHrb** [nsessl/schema#66]
Základem pro vytvoření dobrých pravidel je společný, srozumitelný a v čase neměnný terminologický jazyk. 
Je nutné, aby terminologie byla v souladu i s ostatními normami.

Zde uvedu seznam věcí, které je potřeba postupně vyjasnit a případně opravit, doplnit či sjednotit.
ULOHA-20230621-01: Vytvořit sdílený společný TERMINOLOGICKÝ VÝKLADOVÝ SLOVNÍK uvedený do souladu
pro 
**nařízení Evropského parlamentu a Rady (EU)**
                 [č. 910/2014 EIDAS 1.0](https://esipa.cz/sbirka/sbsrv.dll/sb?DR=SB&CP=32014R0910)

**zákony a jejich přílohy:** 
                  [Zákon č. 297/2016 Sb. Zákon o službách vytvářejících důvěru pro elektronické transakce](https://www.zakonyprolidi.cz/cs/2016-297)
                  [Zákon č. 167/2012 Sb. Zákon změnový k zákonu č. 499/2004 Sb., a k zákonu č. 227/2000 Sb.](https://www.zakonyprolidi.cz/cs/2012-167)
                  [Zákon č. 300/2008 Sb. Zákon o elektronických úkonech a autorizované konverzi dokumentů](https://www.zakonyprolidi.cz/cs/2008-300)
                  [Zákon č. 499/2004 Sb. Zákon o archivnictví a spisové službě a o změně některých zákonů](https://www.zakonyprolidi.cz/cs/2004-499)
                  [Zákon č. 500/2004 Sb. Zákon správní řád](https://www.zakonyprolidi.cz/cs/2004-500)
                  [Zákon č. 227/2000 Sb. Zákon o elektronickém podpisu a o změně některých dalších zákonů](https://www.zakonyprolidi.cz/cs/2000-227)
                  EIDAS 2.0

**pro vyhlášky a jejich přílohy:**
          [VMV č. 10/2023](https://www.mvcr.cz/soubor/vestnik-ministerstva-vnitra-10vmv-pdf.aspx)
          [VMV č. 10/2022](https://www.mvcr.cz/soubor/vestnik-mv-castka-c-10-2022.aspx)
          [VMV č. 57/2017 část II](https://www.mvcr.cz/soubor/vestnik-mv-castka-c-57-2017.aspx)
          [Vyhláška č. 504/2021 Sb. Vyhláška, kterou se mění vyhlášky provádějící zákon o archivnictví a spisové službě](https://www.zakonyprolidi.cz/cs/2021-504)
          [Vyhláška č. 259/2012 Sb. o podrobnostech výkonu spisové služby](https://www.zakonyprolidi.cz/cs/2012-259)
          [Vyhláška č. 190/2009 Sb. Zákon změnový k zákonu č. 499/2004 Sb.](https://www.zakonyprolidi.cz/cs/2009-190)
         
**pro jiné podzákonné normy:** 
           [Metodiky ](https://www.mvcr.cz/clanek/spisova-sluzba-metodiky.aspx)
           Metodický návod pro kontrolu výkonu spisové služby, ...
           Vzorový spisový a skartační plán pro obce 3. stupně
           a další 

**pro vývojovou a ostatní dokumentaci:**
          prováděcí a implementační předpisy, návody, dokumentaci  a pod.
          [Přehled právních předpisů stanovujících povinnost ukládat vybrané typy dokumentů](https://www.mvcr.cz/soubor/pravni-predpisy-skart-lhuty-2021-05-pdf.aspx)

### **Konkrétní příklady:** dokument, Dokument vs komponeta vs soubor.
                              spis vs typový spis vs soubor dokumentů
                              agenda vs věcná skupina

### **Doporučení :** provést sjednocení významů.

A) Výraz dokument vs komponenta vs soubor
Dřívější interpretace výrazu dokument byla "nejmenší jednotka pro zpracování" (list papíru na podatelně, elektronický datový soubor na disku počítače, jeden kotouč s filmem nebo zvukovým záznamem pod.). Programátoři v tomto smyslu použili výraz "soubor" /Jedna písemnost DZ (=soubor nebo XML )/ /[SouborZalozeni()](https://www.mvcr.cz/nsesss/v3/ermsAsynU.xsd)/

Později se tento výraz "dokument" začal užívat ve smyslu spojujícím (skupina listů, jednoelementových dokumentů anebo příloh) . Vnitřní obsah tohoto nového pojetí "dokumentu" se začal označova jako "komponenta". Tím vznikl nesoulad v označeních napříč všem zákonům a normám. (prapůvod současné nepřehlednosti v oblasti národního standardu). 

### **Mé doporučení:**
Dát rovnítko mezi "dokument" a "komponenta" (tj = nejmenší zpracovaný objekt /objekt kterému lze v skartačním řízení přiřadit unikátní identifikátor digitálního archivu a uložit ho do archivu nebo naopak odstranit z ESSL po skartaci a přejímce s trvalým  zachováním jeho metadat/)

Tam, kde je slovo "dokument" použito ve smyslu spojujícím doporučuji použít jiné vhodnější jedno slovo v množném tvaru nebo sousloví (např. listiny, dokumenty, entity, dokumentace, složka dokumentů, sada dokumentů, svazek dokumentů, soubor dokumentů, ... )

### **Důvod:** Znovu začnou dřívější zákony a normy dávat původní smysl aniž by se měnily.
   EIDAS (cca 16x užití výrazu dokument ve smyslu nejmenší prvek k evidenci v ESSL a případně k samostatné archivaci či zničení po uplynutí skartační lhůty) 

  zak.č .č300/2008 Sb (cca 72 x užití výrazu ve smyslu nejmenšího zpracovaného objektu)
  zak č. 500/2008 Sb  ( zmiňuje také dokumenty, spisy a součásti )
  zak č. 499/2004 Sb ( cca 308 x užití výrazu ve smyslu nejmenšího zpracovaného objektu )

Snadné zadefinování výrazu pro skupinu dokumentů v nové verzi ESSL.

**Comment by OAS-Prochazka** [comment]
Děkujeme za Vaši připomínku, podle možností se jí budeme zabývat nejpozději v první polovině roku 2024.

**Comment by OAS-Prochazka** [comment]
Vlákno je rok bez jakékoliv reakce, požadovaná metodická diskuse neproběhla. Komentář garanta XML za ICT Unii: chybí širší shoda.
