### ISSUE TITLE
Skartační režim a druh dokumentu

### ISSUE THREAD

**Issue by JSamkova** [nsessl/schema#67]
Pojem "Druh dokumentu" vyhláška vůbec nezná. Je to pojem, který zavádí NS. A dokonce umožňuje zcela mimo spisový a skartační plán této nové evidenční entitě přidělit skartační režim. Toto pojetí je v rozporu s vyhláškou, protože: 

Vyhláška v par 12 odst. 4 stanoví jednoznačné pravidlo přidělení skartačního režimu dokumentu:  "Veřejnoprávní původce přidělí dokumentu spisový znak a skartační režim spisu, do kterého je zařazen." Tečka.

ALE  ... Bod 6.1.8  NS řeší konflikty, které při dodržení požadavků vyhlášky nemohou nastat: 
" Konflikty vznikají v případech:  ... , a) skartační režim se vztahuje ke spisu v dílu typového spisu a k některým dokumentům v těchto spisech, které současně mají skartační režim přidělen na základě druhu dokumentu,

**Comment by OAS-Prochazka** [comment]
Druhem dokumentu je tematické označení přiřazené dokumentu bez ohledu na jeho zatřídění v hierarchii entit spisové služby. Druhem dokumentu jsou například „faktury“, „smlouvy“ nebo „dokumenty operačního programu XY“. Tento pojem byl zaveden právě v NS z důvodu, že některé dokumenty mohou mít odlišné požadavky na délku skartační lhůty, než vyplývá ze spisu, kde jsou zařazeny. Například ve spisu s lhůtou 5 let může být zařazena faktura se lhůtou 10 let. Přiřazení druhu dokumentu má za úkol zajistit, aby faktura nepřevzala kratší lhůtu ze spisu a nedošlo k jejímu předčasnému vyřazení. Pokud je druhu dokumentu přiřazen skartační režim, může dojít k vyvolání a řešení konfliktu skartačního režimu dokumentu a spisu.
V předchozí verzi NSESSS se místo pojmu Druh dokumentu používal v obdobném významu pojem Typ dokumentu.
