### ISSUE TITLE
Příloha 3 - chybí schéma pro obecné textové dokumenty

### ISSUE THREAD

**Issue by olsansky** [nsessl/schema#68]
Příloha 3 - Struktura popisných metadat pro automatické zpracování dokumentu obsahuje určení schématu popisných metadat pouze pro komponenty typu ISDOC.PDF. Jak je definováno schéma pro komponenty vlastní dokumentů, které nemají charakter elektronických faktur?
Děkuji
JO

**Comment by olsansky** [comment]
Vysvětleno, zavírám

**Comment by backslash47** [comment]
Dobrý den,

mohu poprosit o to vysvětlení ?

MZ

**Comment by kosek** [comment]
Vše definuje příloha 3 (https://github.com/nsessl/schema/blob/develop/Priloha3.md):

> Konkrétní začlenění metadat do jednotlivých formátů definují přímo tyto formáty nebo další samostatné standardy.

V tuto chvíli jediný formát, který začlenění metadat definuje je ISDOC. Pokud někdo něco podobného potřebuje pro další formáty, musí provést obdobnou definici jaké existuje pro ISDOC. Nicméně schéma metadat dokumentu je pořád stejné.
