### ISSUE TITLE
Soucast/Soucasti - Datové typy se stejným názvem (ermsTypes.xsd)

### ISSUE THREAD

**Issue by Ostricker** [nsessl/schema#69]
Ve skupině gTypovySpis existují elementy:
element name="Soucasti"
element name="Soucast"

![gTypovySpis](https://github.com/nsessl/schema/assets/35405301/1c3d72cc-9d8b-489c-a73d-6b7d8053a7f5)

Ve skupině gDilSoucastiTypovehoSpisu existují stejné elementy:
element name="Soucasti"
element name="Soucast"

![gSoucastTypovehoSpisu](https://github.com/nsessl/schema/assets/35405301/9a8275ba-c58d-41c4-8ccf-57b9fb83bdc8)

Při defaultní generaci do Java tříd to vede k nevalidním třídám, protože se vytvoří dva objekty se stejným jménem - Soucasti a Soucast.
Neměla by tam spíš být reference na jeden datový typ?

**Comment by OAS-Prochazka** [comment]
Dotaz jsem předal dál, až dostanu další informace, zveřejním je tu.

**Comment by anthaas** [comment]
Dobrý den, zabývá se někdo timto issue?

**Comment by jakub-ruzicka** [comment]
Nějaký update?

**Comment by OAS-Prochazka** [comment]
Dobrý den, schemata v přílohách standardu v tuto chvíli prochází revizemi, které mají za cíl odstranit chyby a to nejen ty popsané zde ve foru. Revidují se i chyby v textu standardu tak, aby do konce roku mohla být vydána nová, opravená, verze.

**Comment by OAS-Prochazka** [comment]
Problém byl odstraněn v národním standardu platném od 1. 9. 2024.

**Comment by jirikx** [comment]
V [přílohách národního standardu ze stránek MVČR](https://mv.gov.cz/soubor/nsesss-prilohy-20241209-zip.aspx) je tento problém stále přítomný. Pro generování Java kódu jsem vyzkoušel použít Apache CXF i JAX-WS, a v obou případech spadl program při kompilaci na následujících chybách:

```
TTypovySpis.java:[1872,27] class cz.mvcr.nsesss._2024.api.TTypovySpis.Soucasti is already defined in class cz.mvcr.nsesss._2024.api.TTypovySpis
TTypovySpis.java:[1943,31] class cz.mvcr.nsesss._2024.api.TTypovySpis.Soucasti.Soucast is already defined in class cz.mvcr.nsesss._2024.api.TTypovySpis.Soucasti
```

Možná je celá chyba na mé straně, ale raději se zeptám - nesetkal se někdo z vás s tímto problémem v současné verzi standardu také? @Ostricker @jakub-ruzicka

**Comment by kosek** [comment]
Na nové verzi standardu jsem s MV nespolupracoval, nicméně většina knihoven pro databinding umí ručně předefinovat název třídy, na které se komponenta ze schémat mapuje, a tím lze tento typ problému vyřešit, pro JAXB např. zde

https://javaee.github.io/jaxb-v2/doc/user-guide/ch03.html#customization-of-schema-compilation-using-scd-for-customizations

**Comment by jirikx** [comment]
Dobře, děkuji. Myslel jsem, že pracuji se špatným schématem, když je tato issue již uzavřená, ale očividně tomu tak není. Kdyby se někdo setkal se stejným problémem jako já, tak zde přikládám obsah .xjb souboru, se kterým by již měl vzniknout validní Java kód (ty třídy `Soucast` a `Soucasti` si pojmenujte raději nějak smyslupněji :)). Pro generování kódu jsem použil jaxws-ri a jaxws-rt.

```
<jaxb:bindings
  xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  version="3.0">

  <jaxb:bindings schemaLocation="../schemas/ermsTypes.xsd" node="/xs:schema">
    <jaxb:bindings node="//xs:schema/xs:group[@name='gTypovySpis']/xs:sequence/xs:element[@name='Soucasti']/xs:complexType">
      <jaxb:class name="SoucastiOne"/>
    </jaxb:bindings>
    <jaxb:bindings node="//xs:schema//xs:group[@name='gTypovySpis']//xs:sequence//xs:element[@name='Soucasti']//xs:complexType//xs:sequence//xs:element[@name='Soucast']//xs:complexType">
      <jaxb:class name="SoucastOne"/>
    </jaxb:bindings>
    <jaxb:bindings node="//xs:schema/xs:group[@name='gSoucastTypovehoSpisu']/xs:sequence/xs:choice/xs:element[@name='Soucasti']/xs:complexType">
      <jaxb:class name="SoucastiTwo"/>
    </jaxb:bindings>
    <jaxb:bindings node="//xs:schema//xs:group[@name='gSoucastTypovehoSpisu']//xs:sequence//xs:choice//xs:element[@name='Soucasti']//xs:complexType//xs:sequence//xs:element[@name='Soucast']//xs:complexType">
      <jaxb:class name="SoucastTwo"/>
    </jaxb:bindings>
  </jaxb:bindings>
</jaxb:bindings>
```
