### ISSUE TITLE
DokumentSkartacniNavrh; SpisSkartacniNavrh

### ISSUE THREAD

**Issue by mmuzikSeyfor** [nsessl/schema#70]
Prosím, co přesně má tato událost v eSSL provést?

V dokumentaci se píše: 
> Informace o zařazení dokumentu do skartačního návrhu

V NSESSS pak 
> DokumentSkartacniNavrh – informace o zařazení dokumentu do skartačního návrhu s možností vynuceného vyjmutí ze skartačního návrhu v odpovědi na volání události.

ale to je vše, chybí nějaký detailnější popis.

**Comment by OAS-Prochazka** [comment]
Dobrý den, jedná se o to, že eSSL automatizovaně po uplynutí skartační lhůty zařadí dokument do skartačního návrhu. Tato služba informuje ISSD o tom, že eSSL provedl tuto operaci s tím, že ISSD informaci znázorní uživateli, který na to může nebo nemusí reagovat.

**Comment by mmuzikSeyfor** [comment]
Dobrý den, děkuji za odpověď a jakým způsobem má být odopovězeno na "možností vynuceného vyjmutí ze skartačního návrhu v odpovědi na volání události."? 

Pomocí jaké údalosti má ISSD odpovědět, nebo pomocí zprávy? Kde je tato možnost vynuceného vyjmutí vydefinovaná? 

Děkuji

**Comment by OAS-Prochazka** [comment]
Dobrý den, nejasnost asi způsobilo to, že XML je čistě technický popis, který předpokládá metodický popis postupu, který však je obecný a nepopisuje specifický postup komunikace eSSL a ISSD.
Události posílá eSSL do ISSD (přičemž se předpokládá, že událost druhý systém pouze akceptuje). Pokud s nimi nesouhlasí, potom může v rámci přijmu takové události vyhlásit chybový stav (kód a k němu text chyby) a protistrana by se s tím měla nějak vypořádat. ESSL by na toto hlášení nesouhlasu mělo reagovat z logiky věci tak, že dokument vyjme ze skartačního návrhu. (nikde to není přesně takto napsané, ale asi se to dá takto odvodit ze všeho, co tam je uvedeno). U události DokumentSkartováno ISSD již tento stav může jen akceptovat a neměl by již reagovat chybou (i v tomto případě  to není jasně napsáno, ale dá se odvodit z textu NSESSS). Vše uvedené platí i pro spis (události SpisSkartacniNavrh a SpisSkartovano).

**Comment by mmuzikSeyfor** [comment]
Dobrý den, děkuji za odpověď.

**Comment by OAS-Prochazka** [comment]
Ještě doplním, že pokud ISSD bude jakkoliv negativně reagovat (jakákoliv chybová hláška) tak eSSL by také měl nějak reagovat. Popis (chybových hlášek a způsob jejich řešení) stanoví každý eSSL samostatně (NSESSS chybová hlášení nespecifikuje) v rámci dokumentace rozhraní eSSL.
