### ISSUE TITLE
Koncept tFormaUchovani

### ISSUE THREAD

**Issue by marek-vavra** [nsessl/schema#73]
Přestože národní standard nezná pojem rozpracovaného dokumentu (konceptu), a řepokládá uchování všech verzí komponent dokumentu po celou dobu jeho životního cyklu v rámci elektronického systému spisové služby, tak třída tFormaUcování stále pracuje se stavem konceptu, který ovšem nelze využít.

![image](https://github.com/nsessl/schema/assets/149207040/fd786677-9fe0-4ad9-ba6b-b5040c6a2829)

**Comment by OAS-Prochazka** [comment]
NSESSS z r. 2017 s termínem "koncept" pracoval, NSESSS z r. 2023 ho opustil. Ale nezdá se, že by tato změna měla mít vliv na použití pojmu ve formě uchování v rámci SIP. Pořád je nutné pojmově uchopit verzi komponenty, která v případě vlastního dokumentu předchází vzniku originálu (originálem je schválená verze komponenty, často podepsaná a určená k odeslání nebo k jinému finálnímu použití). Typicky je to soubor ve Wordu, který jde k podpisu a exportu do PDF/A a po těchto procesech se tak z něj stává zmíněný originál. Viz https://www.nacr.cz/verejnost/2-predarchivni-pece/verejnopravni-puvodci/informacni-list/castka-6-2020#c3-2020.
