### ISSUE TITLE
Spisový a skartační plán a Simple Type sSpisovyPlan

### ISSUE THREAD

**Issue by jana-obstova** [nsessl/schema#75]
Pro práci se **spisovým a skartačním plánem** národní standard **kapitola 3.1.7** uvádí:
ESSL spravuje spisové a skartační plány, které jsou souhrnem věcných skupin používaných v danou dobu. ESSL vede o spisovém a skartačním plánu alespoň tato metadata:
a) jednoznačný identifikátor,
b) název spisového a skartačního plánu,
c) popis spisového a skartačního plánu,
d) platnost od,
e) platnost do,
f) odkaz na věcné skupiny, které tvoří spisový a skartační plán.

**Problém 1**
Dle definice rozhraní však Simple Type sSpisovyPlan obsahuje pouze string s maximální délkou 100 znaků.

**Otázka**
Jak mají být do typu sSpisovyPlan naplněny atributy uvedené v kapitole národního standardu 3.1.7?

Děkuji za informaci

![image](https://github.com/nsessl/schema/assets/156693700/9f8868d2-b7b0-4459-936a-0127d0289b73)

![image](https://github.com/nsessl/schema/assets/156693700/04a857a2-07a2-4d08-b759-2196f4eb3b71)

**Comment by jana-obstova** [comment]
**Problém 2** 
V příloze 5 (výše řešena příloha 1) pro spisový a skartační plán pro stejnou kapitolu NSESSS je uvedena definice (viz screenshot níže)
Národní standard element Vydavatel vůbec neuvádí. 
Příloha 5 má v Complex Type tSpisovyPlan uveden element Vydavatel jako povinný
Prosím tedy o vyjádření k naplňování elementu Vydavatel.
Děkuji

![image](https://github.com/nsessl/schema/assets/156693700/0c4572a4-efcc-45d3-9885-8c6f3af42c33)

**Comment by OAS-Prochazka** [comment]
Problém byl odstraněn v národním standardu platném od 1. 9. 2024, sSpisovyPlan byl odebrán ze schématu věcné skupiny.
