### ISSUE TITLE
Ztotožnění fyzické osoby podnikající - národní standard 2023 požaduje způsob ztotožnění pro podnikající fyzickou osobu, který základní registry neumožňují

### ISSUE THREAD

**Issue by jana-obstova** [nsessl/schema#76]
**Požadavek národního standardu 2023**
Nový národní standard kapitola 2.8.8 písm. b) ukládá, aby spisová služba umožňovala ztotožnění podle
**jméno, příjmení, datum narození, adresa sídla a právní forma** u **fyzické osoby podnikající**,

![image](https://github.com/nsessl/schema/assets/156693700/9e3ed8e1-78b8-44c9-8bf4-2d8a1b8a4daf)

**Problém**
V ZR neexistuje registr pro podnikající FO. Je možno prohledávat ROB na fyzické osoby a ROS na právnické osoby
Základní registry umožňují 
prohledat ROB minimálně dle údajů: _jméno, příjmení, datum narození_
prohledat ROS minimálně dle  údajů: _obchodní firma nebo název nebo označení a právní forma_
Dle kombinace údajů výše požadovanou v kapitole 2.8.8 písmeno b) subjekt ztotožnit neumožňují

**Otázka**
Prosíme o vyjádření jak má být naplněn požadavek národního standardu 2023 kapitolu 2.8.8 písmeno b)?

**Comment by Merllinn** [comment]
### V případě hledání v testovacích datech ZR pouze podle údajů jméno, příjmení a datm narození:
{
  "agenda":"X999",
  "agendovaRole":"XR2",
  "subjekt":"Subjekt1",
  "uzivatelId":"thubicka",
  "duvodUcel":"ztotozneni",
  "requestMetadata":{
    "jmeno":"Zlata",
    "prijmeni":"Jahodová",
    "datumNarozeni":"1984-08-16"
  }
}

### Dostáváme odpověď:
{
  "status": "SUCCESS",
  "odpovedInfo": {
    "casOdpovedi": "2024-02-20T14:55:06.8373280+01:00",
    "status": {
      "vysledekKod": "VAROVANI",
      "vysledekDetail": {
        "vysledekSubKod": "PREKROCEN SEZNAM",
        "vysledekPopis": ""
      }
    },
    "agendaZadostId": "4bb49156-9138-4d0b-b309-b20f592c8bb6",
    "iszrZadostId": "d82a0a18-1349-1411-9290-19c5fa140001"
  },
  "data": {
    "aplikacniStatus": {
      "vysledekKod": "VAROVANI",
      "vysledekDetail": {
        "vysledekSubKod": "PREKROCEN POCET",
        "vysledekPopis": "CHYBA_0008: Překročen počet povolených záznamů."
      }
    },
    "osoby": []
  }
}

Vyhledávání v ROB tedy není možné pouze podle této kombinace 3 údajů.

**Comment by OAS-Prochazka** [comment]
Vyjádření garanta XML za ICT Unii: Uvedený příklad není v rozporu NS 2.8.8, protože příklad volání je volán špatnou metodou a neobsahuje potřebné atributy. Pravděpodobně jde o nepochopení fungování služeb ISZR.
