### ISSUE TITLE
Drobná chyba ve schématu - námět pro příští verzi

### ISSUE THREAD

**Issue by frantisekfialagordic** [nsessl/schema#78]
V jednom místě je atribut **Zdroj** definován kratší, oproti všem dalším místům. Je to na **ermsAsync** atribut **Zdroj** a je max 6 znaků. Všude jinde je definován jako max 10 znaků. Fakticky to znamená, že se musí všude používat max. 6 znaků, protože významově je to stejná položka.

Ukázka:
![image](https://github.com/nsessl/schema/assets/111127704/4c08359f-94cb-4aff-8222-fd528225f353)

![image](https://github.com/nsessl/schema/assets/111127704/f0b7bb5d-56ff-43bc-bca1-d942a60fdba5)

Pro současnou verzi to není zásadní. Pouze návrh na opravu pro budoucí verzi - asi na max 10 znaků.

**Comment by OAS-Prochazka** [comment]
Problém byl odstraněn v národním standardu platném od 1. 9. 2024, všude opraveno na 10 znaků.
