### ISSUE TITLE
Používat xs:integer místo xs:int

### ISSUE THREAD

**Issue by kosek** [nsessl/schema#8]
xs:int je pouze 16bitové signed číslo, má malý rozsah

**Comment by jakub-ruzicka** [comment]
Nebylo by vhodné spíše u takových elementů požít xs:long?
Naopak mi přijde že u některých elementů je zbytečně použítý xs:integer a mohl by se použít xs:short. Například sPocetZaznamu, který je stejně omezený na hodnotu 1-100.
